/**
 * GET /api/cron/reminder-dispatch
 *
 * Vercel Cron endpoint — runs daily at 11:00 UTC (08:00 BRT, D-04).
 * Scans tomorrow's non-cancelled appointments, enqueues WhatsApp + email reminders
 * into message_outbox per channel, then drains the outbox — all in one invocation.
 *
 * Single-invocation design (RESEARCH Pitfall 1): scan+enqueue+drain in one cron slot
 * so outbox messages are sent same-day rather than stranded until next cron run.
 *
 * SECURITY (T-4-cron-E):
 * - Validates Authorization: Bearer {CRON_SECRET} — 401 on mismatch before any DB query.
 *   Vercel injects CRON_SECRET automatically on scheduled invocation.
 *
 * IDEMPOTENCY (T-4-cron-dup):
 * - message_log UNIQUE(appointment_id, channel, type) — skip if already logged (23505).
 * - message_outbox idempotency_key UNIQUE — enqueue is idempotent (23505 = skip).
 * - drainOutbox selects ONLY status='pending' — already-sent rows are never re-sent.
 *
 * RUNTIME (T-4-cron-runtime): Node.js — Edge has no 'net' module for graph.facebook.com.
 *
 * TENANT ISOLATION (T-4-cron-I):
 * - tenant_id sourced from the appointment row (appt.tenant_id), NEVER from ReminderTarget.
 * - ReminderTarget carries only appointmentId/channel/type/idempotencyKey (no tenant_id).
 */

// CRITICAL: Node.js runtime required (Pitfall 7 — Edge has no 'net' module)
export const runtime = 'nodejs'

import { createAdminClient } from '@/lib/supabase/admin'
import { isCronAuthorized } from '@/lib/cron-auth'
import { logBusinessEvent } from '@/lib/audit'
import { getOutboxQueue } from '@/lib/messaging/queue'
import { drainOutbox } from '@/lib/messaging/worker'
import { selectReminderTargets } from '@/lib/messaging/reminder-scan'
import { toE164 } from '@/lib/phone'
import {
  TEMPLATE_APPOINTMENT_REMINDER,
  WHATSAPP_LANGUAGE,
  buildAppointmentReminderComponents,
} from '@/lib/whatsapp/templates'
import { addDays, startOfDay, format } from 'date-fns'

export async function GET(request: Request) {
  // ── CRON_SECRET validation (T-4-cron-E, CR-01) ──────────────────────────────
  // Vercel injects Authorization: Bearer {CRON_SECRET} on scheduled invocation.
  // isCronAuthorized fails CLOSED (rejects when CRON_SECRET is unset) and uses a
  // constant-time compare — see src/lib/cron-auth.ts. Returns 401 on mismatch
  // before any DB query.
  if (!isCronAuthorized(request.headers.get('authorization'))) {
    return new Response('Unauthorized', { status: 401 })
  }

  const admin = createAdminClient()
  const queue = getOutboxQueue(admin)

  // Tomorrow's date window (UTC — Vercel cron fires at 11:00 UTC = 08:00 BRT)
  const tomorrow = startOfDay(addDays(new Date(), 1))
  const dayAfter = startOfDay(addDays(new Date(), 2))

  let enqueued = 0
  let skipped = 0

  try {
    // ── Scan tomorrow's non-cancelled appointments (RESEARCH §Pattern 6) ──────
    // Dentist name: appointments.dentist_id FK → users(id) but the FK constraint has
    // no explicit name in the migration (auto-generated by Postgres). Rather than risk
    // an incorrect join alias, we fetch dentist names in a single post-query lookup
    // keyed by dentist_id. This is a deliberate choice documented here (D-04).
    // WR-06 (LGPD): exclude soft-deleted / anonymized patients via the inner join —
    // a patient who exercised deletion/opt-out must NOT receive automated reminders.
    // createAdminClient() bypasses RLS, so the soft-delete predicate must be explicit.
    const { data: appointments, error: apptError } = await admin
      .from('appointments')
      .select(`
        id,
        start_time,
        tenant_id,
        dentist_id,
        patients!inner(id, full_name, email, phone, deleted_at, is_anonymized)
      `)
      .gte('start_time', tomorrow.toISOString())
      .lt('start_time', dayAfter.toISOString())
      .neq('status', 'cancelado')
      .is('patients.deleted_at', null)
      .eq('patients.is_anonymized', false)

    if (apptError) {
      console.error('[cron/reminder-dispatch] Failed to load appointments:', apptError.message)
      return Response.json({ error: 'Failed to load appointments' }, { status: 500 })
    }

    if (!appointments || appointments.length === 0) {
      return Response.json({ enqueued: 0, drained: 0, failed: 0, skipped: 0, message: 'No appointments tomorrow' })
    }

    // ── Collect unique dentist IDs and tenant IDs for batch lookups ───────────
    const dentistIds = [...new Set(appointments.map((a) => a.dentist_id).filter(Boolean))]
    const tenantIds = [...new Set(appointments.map((a) => a.tenant_id))]

    // Fetch dentist names (single batch query)
    const dentistMap = new Map<string, string>()
    if (dentistIds.length > 0) {
      const { data: dentists } = await admin
        .from('users')
        .select('id, full_name')
        .in('id', dentistIds as string[])
      for (const d of dentists ?? []) {
        dentistMap.set(d.id, d.full_name)
      }
    }

    // Fetch clinic names per tenant (mirrors collection-ruler clinic name resolution)
    const clinicMap = new Map<string, string>()
    if (tenantIds.length > 0) {
      const { data: clinics } = await admin
        .from('clinics')
        .select('id, name')
        .in('id', tenantIds)
      for (const c of clinics ?? []) {
        clinicMap.set(c.id, c.name)
      }
    }

    // ── Build ScanAppointment[] for selectReminderTargets ─────────────────────
    type AppointmentRow = typeof appointments[number]
    const scanAppointments = appointments.map((appt: AppointmentRow) => {
      const patient = appt.patients as unknown as {
        id: string
        full_name: string
        email: string | null
        phone: string | null
      }
      return {
        id: appt.id,
        start_time: appt.start_time,
        status: 'agendado', // already filtered neq 'cancelado' above; status re-check is defensive
        patient: {
          phone: patient.phone,
          email: patient.email,
        },
      }
    })

    const targets = selectReminderTargets(scanAppointments)

    // Map appointmentId -> source row for tenant_id + patient + dentist lookups
    const apptMap = new Map<string, AppointmentRow>()
    for (const appt of appointments) {
      apptMap.set(appt.id, appt)
    }

    // ── For each target: dedup check + enqueue ────────────────────────────────
    for (const target of targets) {
      const appt = apptMap.get(target.appointmentId)
      if (!appt) continue

      // tenant_id MUST come from the appointment row (T-4-cron-I — not from ReminderTarget)
      const tenantId = appt.tenant_id
      const patient = appt.patients as unknown as {
        id: string
        full_name: string
        email: string | null
        phone: string | null
      }
      const dentistName = appt.dentist_id
        ? (dentistMap.get(appt.dentist_id) ?? 'Dentista')
        : 'Dentista'
      const clinicName = clinicMap.get(tenantId) ?? 'Sua clínica'

      const appointmentDate = format(new Date(appt.start_time), 'dd/MM/yyyy')
      const appointmentTime = format(new Date(appt.start_time), 'HH:mm')

      try {
        // ── message_log dedup INSERT (T-4-cron-dup) ──────────────────────────
        // UNIQUE(appointment_id, channel, type) — 23505 means already reminded.
        const { error: logError } = await admin
          .from('message_log')
          .insert({
            tenant_id: tenantId,
            appointment_id: target.appointmentId,
            channel: target.channel,
            type: '24h',
          })

        if (logError) {
          if (logError.code === '23505') {
            // Already sent for this (appointment, channel, type) — idempotent skip
            skipped++
            continue
          }
          console.error(
            `[cron/reminder-dispatch] Failed to insert message_log for appointment ${target.appointmentId}:`,
            logError.message
          )
          continue
        }

        // ── Build channel-specific JSON-serializable payload (no React elements) ──
        let payload: Record<string, unknown>

        if (target.channel === 'whatsapp') {
          const e164 = toE164(patient.phone)
          if (!e164) {
            // Phone not normalizable to E.164 — skip WhatsApp, leave message_log row
            skipped++
            continue
          }
          payload = {
            kind: 'appointment_reminder',
            to: e164,
            templateName: TEMPLATE_APPOINTMENT_REMINDER,
            languageCode: WHATSAPP_LANGUAGE,
            components: buildAppointmentReminderComponents({
              patientName: patient.full_name,
              date: appointmentDate,
              time: appointmentTime,
              dentistName,
            }),
          }
        } else {
          // email channel — worker.ts email branch detects payload.kind === 'appointment_reminder'
          // and builds: react: createElement(AppointmentReminderEmail, payload.props)
          payload = {
            kind: 'appointment_reminder',
            to: patient.email!,
            subject: `Lembrete: sua consulta é amanhã — ${clinicName}`,
            props: {
              patientName: patient.full_name,
              clinicName,
              appointmentDate,
              appointmentTime,
              dentistName,
            },
          }
        }

        // ── Enqueue into message_outbox (idempotency_key UNIQUE = dedup guard) ──
        const enqueueResult = await queue.enqueue({
          tenantId,
          channel: target.channel,
          idempotencyKey: target.idempotencyKey,
          payload,
        })

        if (!enqueueResult.success) {
          console.error(
            `[cron/reminder-dispatch] Failed to enqueue ${target.channel} for appointment ${target.appointmentId}:`,
            enqueueResult.error
          )
          continue
        }

        enqueued++
      } catch (targetError) {
        console.error(
          `[cron/reminder-dispatch] Error processing target ${target.appointmentId}/${target.channel}:`,
          targetError
        )
        // Continue with next target — one failure should not block others
      }
    }

    // ── Drain the outbox once after all enqueues (Pitfall 1 — send same-day) ──
    // drainOutbox selects ONLY status='pending' — status-idempotent across both crons.
    const drain = await drainOutbox(admin)

    // Audit log — IDs/counts only, no PHI (T-4-cron-I)
    await logBusinessEvent({
      tenantId: appointments[0]?.tenant_id ?? 'system',
      actorId: null,
      action: 'reminder.dispatch_complete',
      details: { enqueued, skipped, drain_processed: drain.processed, drain_failed: drain.failed },
    })

    return Response.json({
      enqueued,
      drained: drain.processed,
      failed: drain.failed,
      skipped,
    })
  } catch (error) {
    console.error('[cron/reminder-dispatch] Fatal error:', error)
    return Response.json({ error: 'Internal server error' }, { status: 500 })
  }
}
